# Generated by Django 3.0.3 on 2020-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browser', '0006_youngmenuhax'),
    ]

    operations = [
        migrations.CreateModel(
            name='gruppapoprokachkegtaonline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('VKLink', models.CharField(max_length=50, verbose_name='VKLink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
