# Generated by Django 3.0.3 on 2020-06-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browser', '0007_gruppapoprokachkegtaonline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='youngmenuhax',
            new_name='indigus_astrakhan',
        ),
        migrations.DeleteModel(
            name='gruppapoprokachkegtaonline',
        ),
    ]
